# Generated by Django 4.2 on 2023-05-18 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('desc', models.CharField(blank=True, max_length=300)),
                ('link', models.CharField(max_length=150)),
                ('img', models.ImageField(default='https://imgur.com/MqHoqdU.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('img', models.ImageField(default='https://imgur.com/MqHoqdU.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('mins', models.IntegerField()),
                ('sec', models.IntegerField()),
                ('date', models.DateField()),
                ('link', models.CharField(max_length=300)),
                ('gif', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.streamer')),
            ],
        ),
    ]
